#!/bin/bash

echo "🚀 Distributed Work Queue Demo Script"
echo "====================================="

echo ""
echo "📋 Available Commands:"
echo ""
echo "1. Start complete system:"
echo "   docker-compose up --build"
echo ""
echo "2. Scale to 2 workers:"
echo "   docker-compose up --scale consumer=2"
echo ""
echo "3. Scale to 3 workers:"
echo "   docker-compose up --scale consumer=3"
echo ""
echo "4. Check running containers:"
echo "   docker-compose ps"
echo ""
echo "5. View logs:"
echo "   docker-compose logs -f"
echo ""
echo "6. Stop one worker:"
echo "   docker-compose kill consumer"
echo ""
echo "7. RabbitMQ Management UI:"
echo "   http://localhost:15672 (guest/guest)"
echo ""
echo "8. Local development (if Docker not available):"
echo "   Terminal 1: WORKER_NAME=worker-1 npm run dev:consumer"
echo "   Terminal 2: WORKER_NAME=worker-2 npm run dev:consumer"
echo "   Terminal 3: npm run dev:producer"
echo ""
echo "🎯 For Evidence Screenshots:"
echo "- Run 'docker-compose up --scale consumer=2' and screenshot the terminal"
echo "- Open http://localhost:15672 and screenshot the queue management"
echo "- Run 'docker-compose ps' to show running containers"
echo "- Stop one worker with Ctrl+C to show task redistribution"